name: auth
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  introduction_screen: ^3.1.12
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  hive_flutter: ^1.1.0
  dio: ^5.4.2+1
  json_annotation: ^4.8.1
  get_it: ^7.6.9
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  talker_flutter: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_bloc_logger: ^4.1.3
  auto_route: ^8.1.0

  cupertino_icons: ^1.0.6
  email_validator: ^2.1.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:  
  auto_route_generator: ^8.0.0  
  retrofit_generator: '>=8.1.0'
  json_serializable: ^6.7.1    
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
