// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHA0Nv7YaNmnRytgx9YrQLH1G1IS1pAoo',
    appId: '1:1068106261605:web:ef9e2124fff1e26339128c',
    messagingSenderId: '1068106261605',
    projectId: 'crypto-coin-list-2be15',
    authDomain: 'crypto-coin-list-2be15.firebaseapp.com',
    storageBucket: 'crypto-coin-list-2be15.appspot.com',
    measurementId: 'G-3KJFG172J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQswhgjDICIYKKBSsaYrAakE3oxZ4NBFw',
    appId: '1:1068106261605:android:491c98cb5ea2f8d039128c',
    messagingSenderId: '1068106261605',
    projectId: 'crypto-coin-list-2be15',
    storageBucket: 'crypto-coin-list-2be15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBSfq4v3aeZ9hf5_lFBps_217Ytxa98_M',
    appId: '1:1068106261605:ios:aa41a5b76b36d5b939128c',
    messagingSenderId: '1068106261605',
    projectId: 'crypto-coin-list-2be15',
    storageBucket: 'crypto-coin-list-2be15.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBSfq4v3aeZ9hf5_lFBps_217Ytxa98_M',
    appId: '1:1068106261605:ios:aa41a5b76b36d5b939128c',
    messagingSenderId: '1068106261605',
    projectId: 'crypto-coin-list-2be15',
    storageBucket: 'crypto-coin-list-2be15.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHA0Nv7YaNmnRytgx9YrQLH1G1IS1pAoo',
    appId: '1:1068106261605:web:039af334e4191bbc39128c',
    messagingSenderId: '1068106261605',
    projectId: 'crypto-coin-list-2be15',
    authDomain: 'crypto-coin-list-2be15.firebaseapp.com',
    storageBucket: 'crypto-coin-list-2be15.appspot.com',
    measurementId: 'G-75GLL2YBLM',
  );

}